artifact_location: /Users/chelynlee/Downloads/MLFlow_Udemy/3_MLFLow_tracking_component/mytracks/0
creation_time: 1763610403092
experiment_id: '0'
last_update_time: 1763610403092
lifecycle_stage: active
name: Default
