artifact_location: /Users/chelynlee/Downloads/MLFlow_Udemy/3_MLFLow_tracking_component/mytracks/736633032514715436
creation_time: 1763610403095
experiment_id: '736633032514715436'
last_update_time: 1763610403095
lifecycle_stage: active
name: exp_for_uri
