artifact_uri: /Users/chelynlee/Downloads/MLFlow_Udemy/3_MLFLow_tracking_component/mytracks/736633032514715436/5bd210671e964ea1885876ff3c9cbdcb/artifacts
end_time: 1763610404362
entry_point_name: ''
experiment_id: '736633032514715436'
lifecycle_stage: active
run_id: 5bd210671e964ea1885876ff3c9cbdcb
run_name: incongruous-hog-452
source_name: ''
source_type: 4
source_version: ''
start_time: 1763610403129
status: 3
tags: []
user_id: chelynlee
